##===----------------------------------------------------------------------===##
##
## This source file is part of the Swift.org open source project
##
## Copyright (c) 2026 Apple Inc. and the Swift.org project authors
## Licensed under Apache License v2.0
##
## See LICENSE.txt for license information
## See CONTRIBUTORS.txt for the list of Swift.org project authors
##
## SPDX-License-Identifier: Apache-2.0
##
##===----------------------------------------------------------------------===##

# Auto-generated by scripts/generate-cli-help-snippets.sh - DO NOT EDIT.
# Run scripts/generate-docs.sh (or this script directly) to regenerate.

# snippet.mainHelp
> swift-java --help

OVERVIEW: Generate sources and configuration for Swift and Java
interoperability.

USAGE: swift-java <subcommand>

OPTIONS:
  -h, --help              Show help information.

SUBCOMMANDS:
  configure               Configure and emit a swift-java.config file based on
                          an input dependency or jar file
  resolve                 Resolve dependencies and write the resulting
                          swift-java.classpath file
  wrap-java               Wrap Java classes with corresponding Swift bindings.
  jextract                Wrap Swift functions and types with Java bindings,
                          making them available to be called from Java

  See 'swift-java help <subcommand>' for detailed help.
# snippet.end

# snippet.configureHelp
> swift-java configure --help

OVERVIEW: Configure and emit a swift-java.config file based on an input
dependency or jar file

USAGE: swift-java configure [--output-directory <output-directory>] [--input-swift <input-swift>] [--log-level <log-level>] [--config <config>] [--cp <cp> ...] [--jar] [--existing-config-file <existing-config-file>] --swift-module <swift-module> [--swift-type-prefix <swift-type-prefix>] [--filter-include <filter-include> ...] [--filter-exclude <filter-exclude> ...]

OPTIONS:
  -o, --output-directory <output-directory>
                          The directory in which to output generated SwiftJava
                          configuration files.
  --input-swift <input-swift>
                          Directory containing Swift files which should be
                          extracted into Java bindings. Also known as
                          'jextract' mode. Must be paired with --output-java
                          and --output-swift.
  -l, --log-level <log-level>
                          Configure the level of logs that should be printed
                          (values: trace, debug, info, notice, warning, error,
                          critical; default: log level)
  --config <config>       A path to a custom swift-java.config to use
  --cp, --classpath <cp>  Class search path of directories and zip/jar files
                          from which Java classes can be loaded.
  --jar                   Specifies that the input is a *.jar file whose public
                          classes will be loaded. The output of swift-java will
                          be a configuration file (swift-java.config) that can
                          be used as input to a subsequent swift-java
                          invocation to generate wrappers for those public
                          classes.
  --existing-config-file <existing-config-file>
                          How to handle an existing swift-java.config; by
                          default 'overwrite' by can be changed to amending a
                          configuration (default: overwrite)
  --swift-module <swift-module>
                          The name of the Swift module into which the resulting
                          Swift types will be generated.
  --swift-type-prefix <swift-type-prefix>
                          A prefix that will be added to the names of the Swift
                          types
  --filter-include <filter-include>
                          While scanning a classpath, inspect ONLY types
                          included in these packages
  --filter-exclude <filter-exclude>
                          While scanning a classpath, skip types which match
                          the filter prefix. You can exclude specific methods
                          by using the `com.example.MyClass#method` format.
  -h, --help              Show help information.

# snippet.end

# snippet.resolveHelp
> swift-java resolve --help

OVERVIEW: Resolve dependencies and write the resulting swift-java.classpath file

USAGE: swift-java resolve [--output-directory <output-directory>] [--input-swift <input-swift>] [--log-level <log-level>] [--config <config>] [--cp <cp> ...] --swift-module <swift-module> [<input>]

ARGUMENTS:
  <input>                 Additional configuration paths (swift-java.config)
                          files, with defined 'dependencies', or dependency
                          descriptors formatted as 'groupID:artifactID:version'
                          separated by ','. May be empty, in which case the
                          target Swift module's configuration's 'dependencies'
                          will be used.

OPTIONS:
  -o, --output-directory <output-directory>
                          The directory in which to output generated SwiftJava
                          configuration files.
  --input-swift <input-swift>
                          Directory containing Swift files which should be
                          extracted into Java bindings. Also known as
                          'jextract' mode. Must be paired with --output-java
                          and --output-swift.
  -l, --log-level <log-level>
                          Configure the level of logs that should be printed
                          (values: trace, debug, info, notice, warning, error,
                          critical; default: log level)
  --config <config>       A path to a custom swift-java.config to use
  --cp, --classpath <cp>  Class search path of directories and zip/jar files
                          from which Java classes can be loaded.
  --swift-module <swift-module>
                          The name of the Swift module into which the resulting
                          Swift types will be generated.
  -h, --help              Show help information.

# snippet.end

# snippet.wrapJavaHelp
> swift-java wrap-java --help

OVERVIEW: Wrap Java classes with corresponding Swift bindings.

USAGE: swift-java wrap-java [<options>] --swift-module <swift-module>

OPTIONS:
  -o, --output-directory <output-directory>
                          The directory in which to output generated SwiftJava
                          configuration files.
  --input-swift <input-swift>
                          Directory containing Swift files which should be
                          extracted into Java bindings. Also known as
                          'jextract' mode. Must be paired with --output-java
                          and --output-swift.
  -l, --log-level <log-level>
                          Configure the level of logs that should be printed
                          (values: trace, debug, info, notice, warning, error,
                          critical; default: log level)
  --config <config>       A path to a custom swift-java.config to use
  --cp, --classpath <cp>  Class search path of directories and zip/jar files
                          from which Java classes can be loaded.
  --swift-module <swift-module>
                          The name of the Swift module into which the resulting
                          Swift types will be generated.
  --depends-on <depends-on>
                          A swift-java configuration file for a given Swift
                          module name on which this module depends,
                          e.g.,
                          JavaKitJar=Sources/JavaKitJar/swift-java.config.
                          There should be one of these options
                          for each Swift module that this module depends on
                          (transitively) that contains wrapped Java sources.
  --swift-native-implementation <swift-native-implementation>
                          The names of Java classes whose declared native
                          methods will be implemented in Swift.
  --cache-directory <cache-directory>
                          Cache directory for intermediate results and other
                          outputs between runs
  --swift-match-package-directory-structure <swift-match-package-directory-structure>
                          Match java package directory structure with generated
                          Swift files (default: false)
  --single-swift-file-output <single-swift-file-output>
                          If specified, a single Swift file will be generated
                          containing all the generated code
  --filter-include <filter-include>
                          While scanning a classpath, inspect ONLY types
                          included in these packages
  --filter-exclude <filter-exclude>
                          While scanning a classpath, skip types which match
                          the filter prefix. You can exclude specific methods
                          by using the `com.example.MyClass#method` format.
  --android-api-version-file <android-api-version-file>
                          Path to Android api-versions.xml for generating
                          @available attributes based on API level data
  -h, --help              Show help information.

# snippet.end

# snippet.jextractHelp
> swift-java jextract --help

OVERVIEW: Wrap Swift functions and types with Java bindings, making them
available to be called from Java

USAGE: swift-java jextract [<options>] --swift-module <swift-module> --output-swift <output-swift> --output-java <output-java>

OPTIONS:
  -o, --output-directory <output-directory>
                          The directory in which to output generated SwiftJava
                          configuration files.
  --input-swift <input-swift>
                          Directory containing Swift files which should be
                          extracted into Java bindings. Also known as
                          'jextract' mode. Must be paired with --output-java
                          and --output-swift.
  -l, --log-level <log-level>
                          Configure the level of logs that should be printed
                          (values: trace, debug, info, notice, warning, error,
                          critical; default: log level)
  --config <config>       A path to a custom swift-java.config to use
  --mode <mode>           The mode of generation to use for the output files.
                          Used with jextract mode.
  --swift-module <swift-module>
                          The name of the Swift module into which the resulting
                          Swift types will be generated.
  --java-package <java-package>
                          The Java package the generated Java code should be
                          emitted into.
  --output-swift <output-swift>
                          The directory where generated Swift files should be
                          written. Generally used with jextract mode.
  --output-java <output-java>
                          The directory where generated Java files should be
                          written. Generally used with jextract mode.
  --write-empty-files/--no-write-empty-files
                          Some build systems require an output to be present
                          when it was 'expected', even if empty. This is used
                          by the JExtractSwiftPlugin build plugin, but
                          otherwise should not be necessary.
  --minimum-input-access-level-mode <minimum-input-access-level-mode>
                          The lowest access level of Swift declarations that
                          should be extracted, defaults to 'public'.
  --memory-management-mode <memory-management-mode>
                          The memory management mode to use for the generated
                          code. By default, the user must explicitly provide
                          `SwiftArena` to all calls that require it. By
                          choosing `allowGlobalAutomatic`, user can omit this
                          parameter and a global GC-based arena will be used.
  --depends-on <depends-on>
                          A swift-java configuration file for a given Swift
                          module name on which this module depends,
                          e.g., Sources/JavaJar/swift-java.config. There should
                          be one of these options
                          for each Swift module that this module depends on
                          (transitively) that contains wrapped Java sources.
  --async-func-mode <async-func-mode>
                          The mode to use for extracting asynchronous Swift
                          functions. By default async methods are extracted as
                          Java functions returning CompletableFuture.
  --enable-java-callbacks/--no-enable-java-callbacks
                          By enabling this mode, JExtract will generate Java
                          code that allows you to implement Swift protocols
                          using Java classes. This feature requires disabling
                          the SwiftPM Sandbox (!). This feature is only
                          supported in 'jni' mode.
  --generated-java-sources-list-file-output <generated-java-sources-list-file-output>
                          If specified, JExtract will output to this file a
                          list of paths to all generated Java source files
  --linker-export-list-output <linker-export-list-output>
                          If specified, JExtract (JNI mode) will write a linker
                          version script to this path. The file lists every
                          generated JNI @_cdecl entry-point symbol as a global
                          export and hides all other symbols with local: *,
                          enabling dead-code elimination of unreachable Swift
                          code:
                            -Xlinker --version-script=<path>
  --filter-include <filter-include>
                          Include only Swift source files matching these
                          patterns during jextract. Patterns are matched
                          against relative file paths (without .swift
                          extension). Supports * (single-segment wildcard) and
                          ** (recursive wildcard). Example: --filter-include
                          'Models/**'
  --filter-exclude <filter-exclude>
                          Exclude Swift source files matching these patterns
                          during jextract. Same pattern syntax as
                          --filter-include. Example: --filter-exclude
                          'Internal/*'
  --single-type <single-type>
                          If specified, only generate bindings for this single
                          Swift type name
  --static-build-config <static-build-config>
                          Path to a JSON file containing a
                          StaticBuildConfiguration. Used to resolve #if
                          conditional compilation blocks.
  -h, --help              Show help information.

# snippet.end
