// Generated by swift-java


#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif


// ==== --------------------------------------------------
// Thunks for DataProtocol

@_cdecl("swiftjava_getType_SwiftRuntimeFunctions_DataProtocol")
public func swiftjava_getType_SwiftRuntimeFunctions_DataProtocol() -> UnsafeMutableRawPointer /* Any.Type */ {
  unsafeBitCast(DataProtocol.self, to: UnsafeMutableRawPointer.self)
}
