// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("org.swift.javakit.dependencies.DependencyResolver")
public struct DependencyResolver {
}

extension JavaClass<DependencyResolver> {
  @JavaStaticMethod
  public func getClasspathWithDependency(dependencies: [String]) throws -> String
}
