// ==== --------------------------------------------------
// Thunks for DataProtocol

// Generated by swift-java

import SwiftJava
import SwiftJavaJNICore
import SwiftJavaRuntimeSupport

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

enum _JNI_DataProtocol {
} // printJNICache(_:_:) @ JExtractSwiftLib/JNISwift2JavaGenerator+SwiftThunkPrinting.swift:177
