// ==== --------------------------------------------------
// Thunks for Data

// Generated by swift-java

import SwiftJava
import SwiftJavaJNICore
import SwiftJavaRuntimeSupport

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

enum _JNI_Data {
} // printJNICache(_:_:) @ JExtractSwiftLib/JNISwift2JavaGenerator+SwiftThunkPrinting.swift:177


#if compiler(>=6.3)
@used
#endif
@_cdecl("Java_org_swift_swiftkit_core_foundation_Data__00024init___3B")
public func Java_org_swift_swiftkit_core_foundation_Data__00024init___3B(environment: UnsafeMutablePointer<JNIEnv?>!, thisClass: jclass, bytes: jbyteArray?) -> jlong {
  let result$ = UnsafeMutablePointer<Data>.allocate(capacity: 1)
  result$.initialize(to: Data.init([UInt8](fromJNI: bytes, in: environment)))
  let resultBits$ = Int64(Int(bitPattern: result$))
  return resultBits$.getJNILocalRefValue(in: environment)
} // printCDecl(_:javaMethodName:parentName:parameters:resultType:_:) @ JExtractSwiftLib/JNISwift2JavaGenerator+SwiftThunkPrinting.swift:819


#if compiler(>=6.3)
@used
#endif
@_cdecl("Java_org_swift_swiftkit_core_foundation_Data__00024getCount__J")
public func Java_org_swift_swiftkit_core_foundation_Data__00024getCount__J(environment: UnsafeMutablePointer<JNIEnv?>!, thisClass: jclass, selfPointer: jlong) -> jlong {
  assert(selfPointer != 0, "selfPointer memory address was null")
  let selfPointerBits$ = Int(Int64(fromJNI: selfPointer, in: environment))
  let selfPointer$ = UnsafeMutablePointer<Data>(bitPattern: selfPointerBits$)
  guard let selfPointer$ else {
    fatalError("selfPointer memory address was null in call to \(#function)!")
  }
  return Int64(selfPointer$.pointee.count).getJNILocalRefValue(in: environment)
} // printCDecl(_:javaMethodName:parentName:parameters:resultType:_:) @ JExtractSwiftLib/JNISwift2JavaGenerator+SwiftThunkPrinting.swift:819

#if compiler(>=6.3)
@used
#endif
@_cdecl("Java_org_swift_swiftkit_core_foundation_Data__00024toByteArray__J")
public func Java_org_swift_swiftkit_core_foundation_Data__00024toByteArray__J(environment: UnsafeMutablePointer<JNIEnv?>!, thisClass: jclass, selfPointer: jlong) -> jbyteArray? {
  guard let env$ = environment else {
    fatalError("Missing JNIEnv in downcall to \(#function)")
  }
  assert(selfPointer != 0, "selfPointer memory address was null")
  let selfPointerBits$ = Int(Int64(fromJNI: selfPointer, in: env$))
  guard let selfPointer$ = UnsafeMutablePointer<Data>(bitPattern: selfPointerBits$) else {
    fatalError("selfPointer memory address was null in call to \(#function)!")
  }
  return selfPointer$.pointee.withUnsafeBytes { buffer in
    buffer.getJNIValue(in: environment)
  }
} // printCDecl(_:javaMethodName:parentName:parameters:resultType:_:) @ JExtractSwiftLib/JNISwift2JavaGenerator+SwiftThunkPrinting.swift:819
#if compiler(>=6.3)
@used
#endif
@_cdecl("Java_org_swift_swiftkit_core_foundation_Data__00024toByteArrayIndirectCopy__J")
public func Java_org_swift_swiftkit_core_foundation_Data__00024toByteArrayIndirectCopy__J(
  environment: UnsafeMutablePointer<JNIEnv?>!,
  thisClass: jclass,
  selfPointer: jlong
) -> jbyteArray? {
  guard let env$ = environment else {
    fatalError("Missing JNIEnv in downcall to \(#function)")
  }
  assert(selfPointer != 0, "selfPointer memory address was null")
  let selfPointerBits$ = Int(Int64(fromJNI: selfPointer, in: env$))
  guard let selfPointer$ = UnsafeMutablePointer<Data>(bitPattern: selfPointerBits$) else {
    fatalError("selfPointer memory address was null in call to \(#function)!")
  }
  // This is a double copy, we need to initialize the array and then copy into a JVM array in getJNIValue
  return [UInt8](selfPointer$.pointee).getJNIValue(in: environment)
} // printCDecl(_:javaMethodName:parentName:parameters:resultType:_:) @ JExtractSwiftLib/JNISwift2JavaGenerator+SwiftThunkPrinting.swift:819

#if compiler(>=6.3)
@used
#endif
@_cdecl("Java_org_swift_swiftkit_core_foundation_Data__00024typeMetadataAddressDowncall__")
public func Java_org_swift_swiftkit_core_foundation_Data__00024typeMetadataAddressDowncall__(environment: UnsafeMutablePointer<JNIEnv?>!, thisClass: jclass) -> jlong {
  let metadataPointer = unsafeBitCast(Data.self, to: UnsafeRawPointer.self)
  return Int64(Int(bitPattern: metadataPointer)).getJNIValue(in: environment)
} // printCDecl(_:javaMethodName:parentName:parameters:resultType:_:) @ JExtractSwiftLib/JNISwift2JavaGenerator+SwiftThunkPrinting.swift:819
