//===----------------------------------------------------------------------===//
// KotlinGeneratorTests.swift
//===----------------------------------------------------------------------===//

import Testing
@testable import JExtractSwiftLib

@Suite("Kotlin Generator Tests")
struct KotlinGeneratorTests {

  // Helper to run the Kotlin generator and return output as a string
  func generateKotlin(input: String) throws -> String {
    var config = Configuration()
    config.swiftModule = "MyModule"

    let translator = Swift2JavaTranslator(config: config)
    translator.log.logLevel = .error
    try translator.analyze(path: "Fake.swift", text: input)

    let generator = KotlinSwift2JavaGenerator(
      config: config,
      translator: translator,
      kotlinOutputDirectory: "/fake"
    )

    return CodePrinter.toString { printer in
      generator.printModule(&printer)
    }
  }

  @Test("Generates object wrapper for module")
  func generatesModuleObject() throws {
    let output = try generateKotlin(input: "public func hello()")
    #expect(output.contains("object MyModule"))
  }

  @Test("Generates header comment")
  func generatesHeader() throws {
    let output = try generateKotlin(input: "public func hello()")
    #expect(output.contains("// Generated by swift-java"))
    #expect(output.contains("// Swift module: MyModule"))
  }

  @Test("Maps Int to Kotlin Int")
  func mapsIntType() throws {
    let output = try generateKotlin(input: "public func add(a: Int, b: Int) -> Int")
    #expect(output.contains("fun add(a: Int, b: Int): Int"))
  }

  @Test("Maps Bool to Kotlin Boolean")
  func mapsBoolType() throws {
    let output = try generateKotlin(input: "public func isEven(n: Int) -> Bool")
    #expect(output.contains("Boolean"))
  }

  @Test("Maps Double to Kotlin Double")
  func mapsDoubleType() throws {
    let output = try generateKotlin(input: "public func area(r: Double) -> Double")
    #expect(output.contains("fun area(r: Double): Double"))
  }

  @Test("Maps String to Kotlin String")
  func mapsStringType() throws {
    let output = try generateKotlin(input: "public func greet(name: String) -> String")
    #expect(output.contains("fun greet(name: String): String"))
  }

  @Test("Maps Void return type to Unit")
  func mapsVoidToUnit() throws {
    let output = try generateKotlin(input: "public func doNothing()")
    #expect(output.contains("fun doNothing()"))
    #expect(!output.contains(": Unit")) // Unit return is implicit in Kotlin
  }

  @Test("Generates TODO stub body")
  func generatesTodoStub() throws {
    let output = try generateKotlin(input: "public func add(a: Int, b: Int) -> Int")
    #expect(output.contains("TODO(\"Not implemented\")"))
  }
}
