# this file is not designed to be run directly
# instead, use the docker-compose.<os>.<swift> files
# eg docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.1604.41.yaml run test
services:

  runtime-setup:
    image: swift-java:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: swift-java:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/swift-java:z
    working_dir: /swift-java
    environment:
      JAVA_HOME: /jdk

  soundness:
    <<: *common
    command: /bin/bash -xcl "swift -version && uname -a && ./scripts/soundness.sh"

  unit-tests:
    <<: *common
    command: /bin/bash -xcl "swift $${SWIFT_TEST_VERB-test} $${WARN_AS_ERROR_ARG-} $${IMPORT_CHECK_ARG-}"

  test-swift:
    <<: *common
    command: /bin/bash -xcl "uname -a && swift -version && /jdk/bin/java -version && swift $${SWIFT_TEST_VERB-test} $${WARN_AS_ERROR_ARG-} $${SANITIZER_ARG-} $${IMPORT_CHECK_ARG-}"

  test-java:
    <<: *common
    command: /bin/bash -xcl "uname -a && swift -version && /jdk/bin/java -version && make jextract-run && ./gradlew test --debug"

  test:
    <<: *common
    command: /bin/bash -xcl "uname -a && swift -version && /jdk/bin/java -version && make jextract-run && swift $${SWIFT_TEST_VERB-test} $${WARN_AS_ERROR_ARG-} $${SANITIZER_ARG-} $${IMPORT_CHECK_ARG-} && ./gradlew test --debug"

  # util

  shell:
    <<: *common
    entrypoint: /bin/bash

