// Generated by jextract-swift
// Swift module: SwiftJava

package org.swift.swiftkit.core.foundation;

import org.swift.swiftkit.core.*;
import org.swift.swiftkit.core.util.*;
import org.swift.swiftkit.core.collections.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;
import org.swift.swiftkit.core.annotations.*;

public final class Data implements JNISwiftInstance, DataProtocol {
  static final String LIB_NAME = "SwiftJava";
  
  @SuppressWarnings("unused")
  private static final boolean INITIALIZED_LIBS = initializeLibs();
  static boolean initializeLibs() {
      System.loadLibrary(SwiftLibraries.LIB_NAME_SWIFT_JAVA);
      System.loadLibrary(LIB_NAME);
      return true;
  }
  /**
  * The designated constructor of any imported Swift types.
  *
  * @param selfPointer  a pointer to the memory containing the value
  * @param swiftArena   the arena this object belongs to. When the arena goes out of scope, this value is destroyed.
  */
  private Data(long selfPointer, SwiftArena swiftArena) {
    SwiftObjects.requireNonZero(selfPointer, "selfPointer");
    this.selfPointer = selfPointer;
    
    // Only register once we have fully initialized the object since this will need the object pointer.
    swiftArena.register(this);
  } // printConcreteType(_:_:) @ JExtractSwiftLib/JNISwift2JavaGenerator+JavaBindingsPrinting.swift:241
  
  /**
   * Assume that the passed {@code long} represents a memory address of a {@link Data}.
   * <p/>
   * Warnings:
   * <ul>
   *   <li>No checks are performed about the compatibility of the pointed at memory and the actual Data types.</li>
   *   <li>This operation does not copy, or retain, the pointed at pointer, so its lifetime must be ensured manually to be valid when wrapping.</li>
   * </ul>
   */
  public static Data wrapMemoryAddressUnsafe(long selfPointer, SwiftArena swiftArena) {
    return new Data(selfPointer, swiftArena);
  }
  
  public static Data wrapMemoryAddressUnsafe(long selfPointer) {
    return new Data(selfPointer, SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA);
  }
  /** Pointer to the "self". */
  private final long selfPointer;
  
  /** Used to track additional state of the underlying object, e.g. if it was explicitly destroyed. */
  private final AtomicBoolean $state$destroyed = new AtomicBoolean(false);
  
  public long $memoryAddress() {
    return this.selfPointer;
  }
  
  @Override
  public AtomicBoolean $statusDestroyedFlag() {
    return $state$destroyed;
  }
  
  
  
  // ==== --------------------------------------------------
  // Data.init
  
  /**
   * Downcall to Swift:
   * {@snippet lang=swift :
   * public init(_ bytes: [UInt8])
   * }
   */
  public static Data init(@Unsigned byte[] bytes, SwiftArena swiftArena) {
    return Data.wrapMemoryAddressUnsafe(Data.$init(Objects.requireNonNull(bytes, "bytes must not be null")), swiftArena);
  } // printJavaBindingWrapperMethod(_:_:importedFunc:skipMethodBody:) @ JExtractSwiftLib/JNISwift2JavaGenerator+JavaBindingsPrinting.swift:693
  private static native long $init(byte[] bytes);
  
  
  
  // ==== --------------------------------------------------
  // getter:Data.count
  
  /**
   * Downcall to Swift:
   * {@snippet lang=swift :
   * public var count: Int
   * }
   */
  public long getCount() {
    return Data.$getCount(this.$memoryAddress());
  } // printJavaBindingWrapperMethod(_:_:importedFunc:skipMethodBody:) @ JExtractSwiftLib/JNISwift2JavaGenerator+JavaBindingsPrinting.swift:693
  private static native long $getCount(long selfPointer);
  
  /**
   * Creates a new Swift @{link Data} instance from a byte array.
   *
   * @param bytes The byte array to copy into the Data
   * @param swiftArena The arena for memory management
   * @return A new Data instance containing a copy of the bytes
   */
  public static Data fromByteArray(byte[] bytes, SwiftArena swiftArena) {
    Objects.requireNonNull(bytes, "bytes cannot be null");
    return Data.init(bytes, swiftArena);
  }
  /**
   * Copies the contents of this Data to a new byte array.
   * 
   * This is a relatively efficient implementation, which avoids native array copies,
   * however it will still perform a copy of the data onto the JVM heap, so use this 
   * only when necessary.
   * 
   * </p> When utmost performance is necessary, you may want to investigate the FFM mode
   * of jextract which is able to map memory more efficiently. 
   *
   * @return A byte array containing a copy of this Data's bytes
   */
  public byte[] toByteArray() {
    return $toByteArray(this.$memoryAddress());
  }
  private static native byte[] $toByteArray(long selfPointer);
  
  /**
   * Copies the contents of this Data to a new byte array.
   * 
   * @deprecated Prefer using the `toByteArray` method as it is more performant.
   * This implementation uses a naive conversion path from native bytes into jbytes 
   * and then copying them onto the jvm heap.
   * 
   * @return A byte array containing a copy of this Data's bytes
   */
  @Deprecated(forRemoval = true)
  public byte[] toByteArrayIndirectCopy() {
    return $toByteArrayIndirectCopy(this.$memoryAddress());
  }
  
  private static native byte[] $toByteArrayIndirectCopy(long selfPointer);
  private static native long $typeMetadataAddressDowncall();
  @Override
  public long $typeMetadataAddress() {
    return Data.$typeMetadataAddressDowncall();
  } // printTypeMetadataAddressFunction(_:_:) @ JExtractSwiftLib/JNISwift2JavaGenerator+JavaBindingsPrinting.swift:785
  
  public String toString() {
    return SwiftObjects.toString(this.$memoryAddress(), this.$typeMetadataAddress());
  }
  
  public String toDebugString() {
    return SwiftObjects.toDebugString(this.$memoryAddress(), this.$typeMetadataAddress());
  }
  
  @Override
  public Runnable $createDestroyFunction() {
    long self$ = this.$memoryAddress();
    long selfType$ = this.$typeMetadataAddress();
    if (CallTraces.TRACE_DOWNCALLS) {
      CallTraces.traceDowncall("Data.$createDestroyFunction",
          "this", this,
          "self", self$);
    }
    return new Runnable() {
      @Override
      public void run() {
        if (CallTraces.TRACE_DOWNCALLS) {
          CallTraces.traceDowncall("Data.$destroy", "self", self$);
        }
        SwiftObjects.destroy(self$, selfType$);
      }
    };
  } // printDestroyFunction(_:_:) @ JExtractSwiftLib/JNISwift2JavaGenerator+JavaBindingsPrinting.swift:799
} // printNominal(_:_:body:) @ JExtractSwiftLib/JNISwift2JavaGenerator+JavaBindingsPrinting.swift:411
