// Generated by jextract-swift
// Swift module: SwiftJava

package org.swift.swiftkit.core.foundation;

import org.swift.swiftkit.core.*;
import org.swift.swiftkit.core.util.*;
import org.swift.swiftkit.core.collections.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;
import org.swift.swiftkit.core.annotations.*;

public final class Date implements JNISwiftInstance {
  static final String LIB_NAME = "SwiftJava";
  
  @SuppressWarnings("unused")
  private static final boolean INITIALIZED_LIBS = initializeLibs();
  static boolean initializeLibs() {
      System.loadLibrary(SwiftLibraries.LIB_NAME_SWIFT_JAVA);
      System.loadLibrary(LIB_NAME);
      return true;
  }
  /**
  * The designated constructor of any imported Swift types.
  *
  * @param selfPointer  a pointer to the memory containing the value
  * @param swiftArena   the arena this object belongs to. When the arena goes out of scope, this value is destroyed.
  */
  private Date(long selfPointer, SwiftArena swiftArena) {
    SwiftObjects.requireNonZero(selfPointer, "selfPointer");
    this.selfPointer = selfPointer;
    
    // Only register once we have fully initialized the object since this will need the object pointer.
    swiftArena.register(this);
  } // printConcreteType(_:_:) @ JExtractSwiftLib/JNISwift2JavaGenerator+JavaBindingsPrinting.swift:241
  
  /**
   * Assume that the passed {@code long} represents a memory address of a {@link Date}.
   * <p/>
   * Warnings:
   * <ul>
   *   <li>No checks are performed about the compatibility of the pointed at memory and the actual Date types.</li>
   *   <li>This operation does not copy, or retain, the pointed at pointer, so its lifetime must be ensured manually to be valid when wrapping.</li>
   * </ul>
   */
  public static Date wrapMemoryAddressUnsafe(long selfPointer, SwiftArena swiftArena) {
    return new Date(selfPointer, swiftArena);
  }
  
  public static Date wrapMemoryAddressUnsafe(long selfPointer) {
    return new Date(selfPointer, SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA);
  }
  /** Pointer to the "self". */
  private final long selfPointer;
  
  /** Used to track additional state of the underlying object, e.g. if it was explicitly destroyed. */
  private final AtomicBoolean $state$destroyed = new AtomicBoolean(false);
  
  public long $memoryAddress() {
    return this.selfPointer;
  }
  
  @Override
  public AtomicBoolean $statusDestroyedFlag() {
    return $state$destroyed;
  }
  
  
  // ==== --------------------------------------------------
  // Date.init
  
  /**
   * Downcall to Swift:
   * {@snippet lang=swift :
   * public init(timeIntervalSince1970: Double)
   * }
   */
  public static Date init(double timeIntervalSince1970, SwiftArena swiftArena) {
    return Date.wrapMemoryAddressUnsafe(Date.$init(timeIntervalSince1970), swiftArena);
  } // printJavaBindingWrapperMethod(_:_:importedFunc:skipMethodBody:) @ JExtractSwiftLib/JNISwift2JavaGenerator+JavaBindingsPrinting.swift:693
  private static native long $init(double timeIntervalSince1970);
  
  
  // ==== --------------------------------------------------
  // getter:Date.timeIntervalSince1970
  
  /**
   * Downcall to Swift:
   * {@snippet lang=swift :
   * public var timeIntervalSince1970: Double
   * }
   */
  public double getTimeIntervalSince1970() {
    return Date.$getTimeIntervalSince1970(this.$memoryAddress());
  } // printJavaBindingWrapperMethod(_:_:importedFunc:skipMethodBody:) @ JExtractSwiftLib/JNISwift2JavaGenerator+JavaBindingsPrinting.swift:693
  private static native double $getTimeIntervalSince1970(long selfPointer);
  
  /**
   * Converts this wrapped date to a Java {@link java.time.Instant}.
   * <p>
   * This method constructs the {@code Instant} using the underlying {@code double} value
   * representing seconds since the Unix Epoch (January 1, 1970).
   * </p>
   *
   * @return A {@code java.time.Instant} derived from the floating-point timestamp.
   */
  public java.time.Instant toInstant() {
      long seconds = (long) this.getTimeIntervalSince1970();
      long nanos = Math.round((this.getTimeIntervalSince1970() - seconds) * 1_000_000_000);
      return java.time.Instant.ofEpochSecond(seconds, nanos);
  }
  
  /**
   * Initializes a Swift {@code Foundation.Date} from a Java {@link java.time.Instant}.
   *
   * <h3>Warning: Precision Loss</h3>
   * <p>
   * <strong>The input precision will be degraded.</strong>
   * </p>
   * <p>
   * Java's {@code Instant} stores time with <strong>nanosecond</strong> precision (9 decimal places).
   * However, this class stores time as a 64-bit floating-point value.
   * </p>
   * <p>
   * This leaves enough capacity for <strong>microsecond</strong> precision (approx. 6 decimal places).
   * </p>
   * <p>
   * Consequently, the last ~3 digits of the {@code Instant}'s nanosecond field will be
   * truncated or subjected to rounding errors during conversion.
   * </p>
   *
   * @param instant The source timestamp to convert.
   * @return A date derived from the input instant with microsecond precision.
   */
  public static Date fromInstant(java.time.Instant instant, SwiftArena swiftArena) {
    Objects.requireNonNull(instant, "Instant cannot be null");
    double timeIntervalSince1970 = instant.getEpochSecond() + (instant.getNano() / 1_000_000_000.0);
    return Date.init(timeIntervalSince1970, swiftArena);
  }
  private static native long $typeMetadataAddressDowncall();
  @Override
  public long $typeMetadataAddress() {
    return Date.$typeMetadataAddressDowncall();
  } // printTypeMetadataAddressFunction(_:_:) @ JExtractSwiftLib/JNISwift2JavaGenerator+JavaBindingsPrinting.swift:785
  
  public String toString() {
    return SwiftObjects.toString(this.$memoryAddress(), this.$typeMetadataAddress());
  }
  
  public String toDebugString() {
    return SwiftObjects.toDebugString(this.$memoryAddress(), this.$typeMetadataAddress());
  }
  
  @Override
  public Runnable $createDestroyFunction() {
    long self$ = this.$memoryAddress();
    long selfType$ = this.$typeMetadataAddress();
    if (CallTraces.TRACE_DOWNCALLS) {
      CallTraces.traceDowncall("Date.$createDestroyFunction",
          "this", this,
          "self", self$);
    }
    return new Runnable() {
      @Override
      public void run() {
        if (CallTraces.TRACE_DOWNCALLS) {
          CallTraces.traceDowncall("Date.$destroy", "self", self$);
        }
        SwiftObjects.destroy(self$, selfType$);
      }
    };
  } // printDestroyFunction(_:_:) @ JExtractSwiftLib/JNISwift2JavaGenerator+JavaBindingsPrinting.swift:799
} // printNominal(_:_:body:) @ JExtractSwiftLib/JNISwift2JavaGenerator+JavaBindingsPrinting.swift:411
