//===----------------------------------------------------------------------===//
// KotlinSwift2JavaGenerator.swift
// Generates Kotlin JVM stubs from imported Swift declarations.
//===----------------------------------------------------------------------===//

import SwiftJavaConfigurationShared
import struct Foundation.URL
import Foundation

package class KotlinSwift2JavaGenerator: Swift2JavaGenerator {
  let config: Configuration
  let analysis: AnalysisResult
  let swiftModuleName: String
  let kotlinOutputDirectory: String

  package init(
    config: Configuration,
    translator: Swift2JavaTranslator,
    kotlinOutputDirectory: String
  ) {
    self.config = config
    self.analysis = translator.result
    self.swiftModuleName = translator.swiftModuleName
    self.kotlinOutputDirectory = kotlinOutputDirectory
  }

  package func generate() throws {
    var printer = CodePrinter()
    printModule(&printer)

    let outputDir = URL(fileURLWithPath: kotlinOutputDirectory)
    try FileManager.default.createDirectory(at: outputDir, withIntermediateDirectories: true)

    let outputFile = outputDir.appendingPathComponent("\(swiftModuleName).kt")
    try printer.contents.write(to: outputFile, atomically: true, encoding: .utf8)

    print("Generated Kotlin: \(outputFile.path)")
  }

  func printModule(_ printer: inout CodePrinter) {
    // Header
    printer.print(
      """
      // Generated by swift-java
      // Swift module: \(swiftModuleName)

      """
    )

    // Module object
    printer.printBraceBlock("object \(swiftModuleName)") { printer in
      for decl in analysis.importedGlobalFuncs {
        printFunction(&printer, decl)
      }
    }
  }

  func printFunction(_ printer: inout CodePrinter, _ decl: ImportedFunc) {
    let params = decl.functionSignature.parameters
      .enumerated()
      .map { (i, param) in
        let name = param.parameterName ?? "_\(i)"
        let type = mapSwiftTypeToKotlin(param.type)
        return "\(name): \(type)"
      }
      .joined(separator: ", ")

    let returnType = mapSwiftTypeToKotlin(decl.functionSignature.result.type)
    let returnClause = returnType == "Unit" ? "" : ": \(returnType)"

    printer.print("fun \(decl.name)(\(params))\(returnClause) = TODO(\"Not implemented\")")
  }

  func mapSwiftTypeToKotlin(_ type: SwiftType) -> String {
    // Get the type name as a string and map it
    let typeName = "\(type)"

    switch typeName {
    case "Int":              return "Int"
    case "Int64":            return "Long"
    case "Int32":            return "Int"
    case "Bool":             return "Boolean"
    case "Double":           return "Double"
    case "Float":            return "Float"
    case "String":           return "String"
    case "Void", "()":       return "Unit"
    default:                 return typeName
    }
  }
}
