/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_swift_HelloJava2Swift */

#ifndef _Included_com_example_swift_HelloJava2Swift
#define _Included_com_example_swift_HelloJava2Swift
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_swift_HelloJava2Swift
 * Method:    jniWriteString
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_swift_HelloJava2Swift_jniWriteString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_swift_HelloJava2Swift
 * Method:    jniGetInt
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_swift_HelloJava2Swift_jniGetInt
  (JNIEnv *, jclass);

/*
 * Class:     com_example_swift_HelloJava2Swift
 * Method:    add
 * Signature: (Ljava/lang/Integer;Ljava/lang/Integer;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_swift_HelloJava2Swift_add
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
