name: 'Swift Java CI Env'
description: 'Prepare the CI environment by installing Swift and selected JDK etc.'

runs:
  using: composite
  steps:
    - name: Set up JDK ${{ matrix.jdk_version }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.jdk_vendor }}
        java-version: |
          24
          21
        cache: 'gradle'
    - name: Set JDK21
      shell: bash
      run: |
        if [[ -n "$JAVA_HOME_21_X64" ]]; then
          echo "JDK21=$JAVA_HOME_21_X64" >> $GITHUB_ENV
        elif [[ -n "$JAVA_HOME_21_ARM64" ]]; then
          echo "JDK21=$JAVA_HOME_21_ARM64" >> $GITHUB_ENV
        fi
    - name: Set JDK24
      shell: bash
      run: |
        if [[ -n "$JAVA_HOME_24_X64" ]]; then
          echo "JDK24=$JAVA_HOME_24_X64" >> $GITHUB_ENV
        elif [[ -n "$JAVA_HOME_24_ARM64" ]]; then
          echo "JDK24=$JAVA_HOME_24_ARM64" >> $GITHUB_ENV
        fi
    - name: Check Java environment
      shell: bash
      run: ./gradlew -q javaToolchains
      env:
        JDK21: ${{ env.JAVA_HOME_21_X64 || env.JAVA_HOME_21_ARM64 }}
    - name: Cache local SwiftPM repository
      if: matrix.os_version == 'jammy'
      uses: actions/cache@v4
      continue-on-error: true
      with:
        path: /__w/swift-java/swift-java/.build/checkouts
        key: ${{ runner.os }}-swiftpm-cache-${{ hashFiles('Package.swift') }}
        restore-keys: |
          ${{ runner.os }}-swiftpm-cache
          ${{ runner.os }}-swiftpm-
