name: 'Swift Java CI Env'
description: 'Prepare the CI environment by installing Swift and selected JDK etc.'

runs:
  using: composite
  steps:
    - name: Set up JDK ${{ matrix.jdk_version }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.jdk_vendor }}
        java-version: |
          24
          21
        cache: 'gradle'
    - name: Re-export JAVA_HOME
      run: >
        # Gradle specifically looks for JDK_N environment variables to detect installed JDK versions,
        # so we need to ensure it can find it, so it picks up JDK_24 since we are using 21 for Gradle itself,
        # because it does not (yet) support JDK 24+. If it did, we wouldn't need multiple JDKs installed.
        if [[ -n "$JAVA_HOME_24_ARM64" ]]; then echo "JDK_24=${{ env.JAVA_HOME_24_ARM64 }}" >> "$GITHUB_ENV"; fi;
        if [[ -n "$JAVA_HOME_24_X64" ]]; then echo "JDK_24=${{ env.JAVA_HOME_24_X64 }}" >> "$GITHUB_ENV"; fi;
        if [[ -n "$JAVA_HOME_21_ARM64" ]]; then echo "JDK_21=${{ env.JAVA_HOME_21_ARM64 }}" >> "$GITHUB_ENV"; fi;
        if [[ -n "$JAVA_HOME_21_X64" ]]; then echo "JDK_21=${{ env.JAVA_HOME_21_X64 }}" >> "$GITHUB_ENV"; fi;
        echo $JDK_21; 
        echo $JDK_24;
      shell: bash
    - name: Check Java environment
      run: |
        env | grep JAVA_HOME;  
        env | grep JDK; 
        ./gradlew -q javaToolchains
      shell: bash
    - name: Cache local SwiftPM repository
      if: matrix.os_version == 'jammy'
      uses: actions/cache@v4
      continue-on-error: true
      with:
        path: /__w/swift-java/swift-java/.build/checkouts
        key: ${{ runner.os }}-swiftpm-cache-${{ hashFiles('Package.swift') }}
        restore-keys: |
          ${{ runner.os }}-swiftpm-cache
          ${{ runner.os }}-swiftpm-
