#!/bin/bash
##===----------------------------------------------------------------------===##
##
## This source file is part of the Swift.org open source project
##
## Copyright (c) 2026 Apple Inc. and the Swift.org project authors
## Licensed under Apache License v2.0
##
## See LICENSE.txt for license information
## See CONTRIBUTORS.txt for the list of Swift.org project authors
##
## SPDX-License-Identifier: Apache-2.0
##
##===----------------------------------------------------------------------===##
##
## Captures the live --help output of the swift-java CLI and writes it to
## Snippets/SwiftJavaCLIHelp.txt, sliced per subcommand so the DocC pages can
## embed the *actual* --help/USAGE text via @Snippet instead of a pasted copy
## that can drift out of sync with the tool.
##
## Usage:
##   scripts/generate-cli-help-snippets.sh
##
set -eu

cd "$(dirname "$0")/.."

OUTPUT_FILE="Snippets/SwiftJavaCLIHelp.txt"

echo "Building swift-java..."
swift build --product swift-java
BIN_PATH="$(swift build --product swift-java --show-bin-path)/swift-java"

# Subcommand:slice pairs to capture, in the order they should appear if ever
# listed together. Keep in sync with the subcommands array in
# Sources/SwiftJavaTool/SwiftJava.swift (excluding commands with
# `shouldDisplay: false`, e.g. java-callbacks-build).
SUBCOMMAND_SLICES=(
  "configure:configureHelp"
  "resolve:resolveHelp"
  "wrap-java:wrapJavaHelp"
  "jextract:jextractHelp"
)

echo "Capturing --help output into $OUTPUT_FILE..."
{
  cat <<'HEADER'
##===----------------------------------------------------------------------===##
##
## This source file is part of the Swift.org open source project
##
## Copyright (c) 2026 Apple Inc. and the Swift.org project authors
## Licensed under Apache License v2.0
##
## See LICENSE.txt for license information
## See CONTRIBUTORS.txt for the list of Swift.org project authors
##
## SPDX-License-Identifier: Apache-2.0
##
##===----------------------------------------------------------------------===##

# Auto-generated by scripts/generate-cli-help-snippets.sh - DO NOT EDIT.
# Run scripts/generate-docs.sh (or this script directly) to regenerate.
HEADER

  echo
  echo "# snippet.mainHelp"
  echo "> swift-java --help"
  echo
  "$BIN_PATH" --help
  echo "# snippet.end"

  for entry in "${SUBCOMMAND_SLICES[@]}"; do
    subcommand="${entry%%:*}"
    slice="${entry##*:}"
    echo
    echo "# snippet.${slice}"
    echo "> swift-java $subcommand --help"
    echo
    "$BIN_PATH" "$subcommand" --help
    echo "# snippet.end"
  done
} > "$OUTPUT_FILE"

echo "Done."
