//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2026 Apple Inc. and the Swift.org project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of Swift.org project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import SwiftJava

/// A Swift error that knows how to turn itself into a dedicated Java exception.
///
/// Conformances are generated by jextract.
public protocol _JNIThrowableError: Error {
  func _makeJavaThrowable(in environment: JNIEnvironment) -> jthrowable?
}

extension JNIEnvironment {
  /// Convert the given Swift error into a Java `Throwable`.
  ///
  /// - A Java `Throwable` is passed through as is.
  /// - A ``_JNIThrowableError`` is converted to its dedicated Java exception class.
  /// - Any other error is boxed in a `SwiftJavaErrorException`.
  public func makeJavaThrowable(for error: any Error) -> jthrowable? {
    // If we're throwing something that's already a Java Throwable object,
    // use it directly.
    if let javaObject = error as? any AnyJavaObject,
      let throwable = javaObject.as(Throwable.self)
    {
      return throwable.javaThis
    }

    if let throwableError = error as? any _JNIThrowableError {
      return throwableError._makeJavaThrowable(in: self)
    }
    return makeSwiftJavaErrorException(for: error)
  }

  /// Throw the given Swift error as a Java exception.
  public func throwSwiftErrorAsJava(_ error: any Error) {
    guard let throwable = makeJavaThrowable(for: error) else {
      return
    }
    _ = interface.Throw(self, throwable)
  }

  /// Box the error in a `SwiftJavaErrorException`.
  private func makeSwiftJavaErrorException(for error: any Error) -> jthrowable? {
    let selfPointer$ = UnsafeMutablePointer<any Error>.allocate(capacity: 1)
    selfPointer$.initialize(to: error)
    let selfPointerBits$ = Int64(Int(bitPattern: selfPointer$))
    let metadata$ = unsafeBitCast((any Error).self, to: UnsafeRawPointer.self)
    let metadataBits$ = Int64(Int(bitPattern: metadata$))
    var args = [jvalue(), jvalue()]
    args[0].j = selfPointerBits$.getJNIValue(in: self)
    args[1].j = metadataBits$.getJNIValue(in: self)
    return interface.CallStaticObjectMethodA(
      self,
      _JNIMethodIDCache.SwiftJavaErrorException.class,
      _JNIMethodIDCache.SwiftJavaErrorException.wrapMemoryAddressUnsafe,
      &args
    )
  }
}
