//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2025 Apple Inc. and the Swift.org project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of Swift.org project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import JExtractSwiftLib
import Testing

@Suite
struct JNIClassTests {
  let source = """
    public class MyClass {
      public static func method() {
  
      }
    }
  """

  @Test
  func generatesJavaClass() throws {
    try assertOutput(input: source, .jni, .java, expectedChunks: [
      """
      // Generated by jextract-swift
      // Swift module: SwiftModule

      package com.example.swift;

      public final class MyClass {
      """
    ])
  }

  @Test
  func staticMethod_javaBindings() throws {
    try assertOutput(
      input: source,
      .jni,
      .java,
      expectedChunks: [
        """
        /**
          * Downcall to Swift:
          * {@snippet lang=swift :
          * public static func method()
          * }
          */
        public static native void method();
        """
      ]
    )
  }

  @Test
  func staticMethod_swiftThunks() throws {
    try assertOutput(
      input: source,
      .jni,
      .swift,
      detectChunkByInitialLines: 1,
      expectedChunks: [
        """
        @_cdecl("Java_com_example_swift_MyClass_method")
        func swiftjava_SwiftModule_MyClass_method(environment: UnsafeMutablePointer<JNIEnv?>!, thisClass: jclass) {
          MyClass.method()
        }
        """
      ]
    )
  }
}
