//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2025 Apple Inc. and the Swift.org project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of Swift.org project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import CodePrinting
import JExtractSwiftLib
import SwiftJavaConfigurationShared
import Testing

@Suite
struct JNIEnumTests {
  let source = """
    public struct MyValue {}

    public enum MyEnum {
      case first
      case second(String)
      case third(x: Int64, y: Int32, MyValue)
    }
    """

  @Test
  func generatesJavaClass() throws {
    try assertOutput(
      input: source,
      .jni,
      .java,
      expectedChunks: [
        """
        // Generated by jextract-swift
        // Swift module: SwiftModule

        package com.example.swift;

        import org.swift.swiftkit.core.*;
        import org.swift.swiftkit.core.util.*;
        import org.swift.swiftkit.core.collections.*;
        import java.util.*;
        import java.util.concurrent.atomic.AtomicBoolean;
        import org.swift.swiftkit.core.annotations.*;
        """,
        """
        public final class MyEnum implements JNISwiftInstance {
          static final java.lang.String LIB_NAME = "SwiftModule";

          @SuppressWarnings("unused")
          private static final boolean INITIALIZED_LIBS = initializeLibs();
          static boolean initializeLibs() {
            SwiftLibraries.loadLibraryWithFallbacks(SwiftLibraries.LIB_NAME_SWIFT_JAVA);
            SwiftLibraries.loadLibraryWithFallbacks(LIB_NAME);
            return true;
          }
        """,
        """
        private MyEnum(long selfPointer, SwiftArena swiftArena) {
          SwiftObjects.requireNonZero(selfPointer, "selfPointer");
          this.selfPointer = selfPointer;

          // Only register once we have fully initialized the object since this will need the object pointer.
          swiftArena.register(this);
        }
        """,
        """
        private final long selfPointer;
        """,
        """
        public long $memoryAddress() {
          return this.selfPointer;
        }
        """,
        """
        public static MyEnum wrapMemoryAddressUnsafe(long selfPointer, SwiftArena swiftArena) {
          return new MyEnum(selfPointer, swiftArena);
        }
        """,
        """
        @Override
        public Runnable $createDestroyFunction() {
          long self$ = this.$memoryAddress();
          long selfType$ = this.$typeMetadataAddress();
          if (CallTraces.TRACE_DOWNCALLS) {
            CallTraces.traceDowncall("MyEnum.$createDestroyFunction",
                "this", this,
                "self", self$);
          }
          return new Runnable() {
            @Override
            public void run() {
              if (CallTraces.TRACE_DOWNCALLS) {
                CallTraces.traceDowncall("MyEnum.$destroy", "self", self$);
              }
              SwiftObjects.destroy(self$, selfType$);
            }
          };
        }
        """,
      ]
    )
  }

  @Test
  func generatesDiscriminator_java() throws {
    try assertOutput(
      input: source,
      .jni,
      .java,
      detectChunkByInitialLines: 2,
      expectedChunks: [
        """
        public enum Discriminator {
          FIRST,
          SECOND,
          THIRD
        }
        """,
        """
        public Discriminator getDiscriminator() {
          var raw = SwiftObjects.getRawDiscriminator(this.$memoryAddress(), this.$typeMetadataAddress());
          return Discriminator.values()[raw];
        }
        """,
      ]
    )
  }

  @Test
  func generatesDiscriminator_swift() throws {
    try assertOutput(
      input: source,
      .jni,
      .swift,
      detectChunkByInitialLines: 1,
      expectedChunks: [
        """
        extension MyEnum: _RawDiscriminatorRepresentable {
          public var _rawDiscriminator: Int32 {
            switch self {
              case .first: return 0
              case .second: return 1
              case .third: return 2
            }
          }
        }
        """
      ]
    )
  }

  @Test
  func generatesCases_java() throws {
    try assertOutput(
      input: source,
      .jni,
      .java,
      detectChunkByInitialLines: 1,
      expectedChunks: [
        """
        public sealed interface Case {
          record First() implements Case {}
          record Second(java.lang.String arg0) implements Case {}
          record Third(long x, int y, MyValue arg2) implements Case {}
        }
        """,
        """
        public Case getCase(SwiftArena swiftArena) {
          return switch (this.getDiscriminator()) {
            case FIRST -> this.getAsFirst().orElseThrow();
            case SECOND -> this.getAsSecond().orElseThrow();
            case THIRD -> this.getAsThird(swiftArena).orElseThrow();
          }
        }
        """,
      ]
    )
  }

  @Test
  func generatesCaseInitializers_java() throws {
    try assertOutput(
      input: source,
      .jni,
      .java,
      detectChunkByInitialLines: 1,
      expectedChunks: [
        """
        public static MyEnum first(SwiftArena swiftArena) {
          return MyEnum.wrapMemoryAddressUnsafe(MyEnum.$first(), swiftArena);
        }
        """,
        """
        public static MyEnum second(java.lang.String arg0, SwiftArena swiftArena) {
          return MyEnum.wrapMemoryAddressUnsafe(MyEnum.$second(arg0), swiftArena);
        }
        """,
        """
        public static MyEnum third(long x, int y, MyValue arg2, SwiftArena swiftArena) {
          return MyEnum.wrapMemoryAddressUnsafe(MyEnum.$third(x, y, arg2.$memoryAddress()), swiftArena);
        }
        """,
      ]
    )
  }

  @Test
  func generatesCaseInitializers_swift() throws {
    try assertOutput(
      input: source,
      .jni,
      .swift,
      detectChunkByInitialLines: 1,
      expectedChunks: [
        """
        @_cdecl("Java_com_example_swift_MyEnum__00024first__")
        public func Java_com_example_swift_MyEnum__00024first__(environment: UnsafeMutablePointer<JNIEnv?>!, thisClass: jclass) -> jlong {
          let result$ = UnsafeMutablePointer<MyEnum>.allocate(capacity: 1)
          result$.initialize(to: MyEnum.first)
          let resultBits$ = Int64(Int(bitPattern: result$))
          return resultBits$.getJNILocalRefValue(in: environment)
        }
        """,
        """
        @_cdecl("Java_com_example_swift_MyEnum__00024second__Ljava_lang_String_2")
        public func Java_com_example_swift_MyEnum__00024second__Ljava_lang_String_2(environment: UnsafeMutablePointer<JNIEnv?>!, thisClass: jclass, arg0: jstring?) -> jlong {
          let result$ = UnsafeMutablePointer<MyEnum>.allocate(capacity: 1)
          result$.initialize(to: MyEnum.second(String(fromJNI: arg0, in: environment)))
          let resultBits$ = Int64(Int(bitPattern: result$))
          return resultBits$.getJNILocalRefValue(in: environment)
        }
        """,
        """
        @_cdecl("Java_com_example_swift_MyEnum__00024third__JIJ")
        public func Java_com_example_swift_MyEnum__00024third__JIJ(environment: UnsafeMutablePointer<JNIEnv?>!, thisClass: jclass, x: jlong, y: jint, arg2: jlong) -> jlong {
          assert(arg2 != 0, "arg2 memory address was null")
          let arg2Bits$ = Int(Int64(fromJNI: arg2, in: environment))
          let arg2$ = UnsafeMutablePointer<MyValue>(bitPattern: arg2Bits$)
          guard let arg2$ else {
            fatalError("arg2 memory address was null in call to \\(#function)!")
          }
          let result$ = UnsafeMutablePointer<MyEnum>.allocate(capacity: 1)
          result$.initialize(to: MyEnum.third(x: Int64(fromJNI: x, in: environment), y: Int32(fromJNI: y, in: environment), arg2$.pointee))
          let resultBits$ = Int64(Int(bitPattern: result$))
          return resultBits$.getJNILocalRefValue(in: environment)
        }
        """,
      ]
    )
  }

  @Test
  func generatesGetAsCase_java() throws {
    try assertOutput(
      input: source,
      .jni,
      .java,
      detectChunkByInitialLines: 1,
      expectedChunks: [
        """
        public java.util.Optional<Case.First> getAsFirst() {
          if (getDiscriminator() != Discriminator.FIRST) {
            return Optional.empty();
          }
          return Optional.of(new Case.First());
        }
        """,
        """
        public java.util.Optional<Case.Second> getAsSecond() {
          if (getDiscriminator() != Discriminator.SECOND) {
            return Optional.empty();
          }
          Case.Second._NativeParameters $nativeParameters = MyEnum.$getAsSecond(this.$memoryAddress());
          return Optional.of(new Case.Second($nativeParameters.arg0));
        }
        """,
        """
        public java.util.Optional<Case.Third> getAsThird(SwiftArena swiftArena) {
          if (getDiscriminator() != Discriminator.THIRD) {
            return Optional.empty();
          }
          Case.Third._NativeParameters $nativeParameters = MyEnum.$getAsThird(this.$memoryAddress());
          return Optional.of(new Case.Third($nativeParameters.x, $nativeParameters.y, MyValue.wrapMemoryAddressUnsafe($nativeParameters.arg2, swiftArena)));
        }
        """,
      ]
    )
  }

  @Test
  func generatesGetAsCase_swift() throws {
    try assertOutput(
      input: source,
      .jni,
      .swift,
      detectChunkByInitialLines: 1,
      expectedChunks: [
        """
        enum _JNI_MyEnum {
          static let myEnumSecondCache = _JNIMethodIDCache(className: "com/example/swift/MyEnum$Case$Second$_NativeParameters", methods: [.init(name: "<init>", signature: "(Ljava/lang/String;)V")])
          static let myEnumThirdCache = _JNIMethodIDCache(className: "com/example/swift/MyEnum$Case$Third$_NativeParameters", methods: [.init(name: "<init>", signature: "(JIJ)V")])
        }
        """,
        """
        @_cdecl("Java_com_example_swift_MyEnum__00024getAsSecond__J")
        public func Java_com_example_swift_MyEnum__00024getAsSecond__J(environment: UnsafeMutablePointer<JNIEnv?>!, thisClass: jclass, selfPointer: jlong) -> jobject? {
          ...
          guard case .second(let _0) = selfPointer$.pointee else {
            fatalError("Expected enum case 'second', but was '\\(selfPointer$.pointee)'!")
          }
          let cache$ = _JNI_MyEnum.myEnumSecondCache
          let class$ = cache$.javaClass
          let method$ = _JNIMethodIDCache.Method(name: "<init>", signature: "(Ljava/lang/String;)V")
          let constructorID$ = cache$[method$]
          let newObjectArgs$: [jvalue] = [jvalue(l: _0.getJNILocalRefValue(in: environment) ?? nil)]
          return environment.interface.NewObjectA(environment, class$, constructorID$, newObjectArgs$)
        }
        """,
        """
        @_cdecl("Java_com_example_swift_MyEnum__00024getAsThird__J")
        public func Java_com_example_swift_MyEnum__00024getAsThird__J(environment: UnsafeMutablePointer<JNIEnv?>!, thisClass: jclass, selfPointer: jlong) -> jobject? {
          ...
          guard case .third(let x, let y, let _2) = selfPointer$.pointee else {
            fatalError("Expected enum case 'third', but was '\\(selfPointer$.pointee)'!")
          }
          let cache$ = _JNI_MyEnum.myEnumThirdCache
          let class$ = cache$.javaClass
          let method$ = _JNIMethodIDCache.Method(name: "<init>", signature: "(JIJ)V")
          let constructorID$ = cache$[method$]
          let arg2$ = UnsafeMutablePointer<MyValue>.allocate(capacity: 1)
          arg2$.initialize(to: _2)
          let arg2Bits$ = Int64(Int(bitPattern: arg2$))
          let newObjectArgs$: [jvalue] = [jvalue(j: x.getJNILocalRefValue(in: environment)), jvalue(i: y.getJNILocalRefValue(in: environment)), jvalue(j: arg2Bits$.getJNILocalRefValue(in: environment))]
          return environment.interface.NewObjectA(environment, class$, constructorID$, newObjectArgs$)
        }
        """,
      ],
      notExpectedChunks: [
        "public func Java_com_example_swift_MyEnum__00024getAsFirst__J("
      ]
    )
  }

  @Test
  func nonGeneratesGetAsCase_swift() throws {
    try assertOutput(
      input: """
        public enum MyEnum {
          case first
          case second
        }
        """,
      .jni,
      .swift,
      detectChunkByInitialLines: 1,
      expectedChunks: [],
      notExpectedChunks: [
        """
        enum _JNI_MyEnum
        """,
        """
        public func Java_com_example_swift_MyEnum__00024getAsFirst__J("
        """,
        """
        public func Java_com_example_swift_MyEnum__00024getAsSecond__J(
        """,
      ]
    )
  }

  @Test
  func invalidRedeclaration() throws {
    let input = """
      public enum DeliveryStage : Swift.String, Swift.Sendable & Swift.Codable {
        case schedule
        case delivered
        public init?(rawValue: Swift.String)
        public typealias RawValue = Swift.String
        public var rawValue: Swift.String {
          get
        }
      }
      """

    var config = Configuration()
    config.swiftModule = "SwiftModule"
    let translator = Swift2JavaTranslator(config: config)
    try! translator.analyze(path: "/fake/Fake.swiftinterface", text: input)

    var printer: CodePrinter = CodePrinter(mode: .accumulateAll)
    let generator = JNISwift2JavaGenerator(
      config: config,
      translator: translator,
      javaPackage: "com.example.swift",
      swiftOutputDirectory: "/fake",
      javaOutputDirectory: "/fake",
      javaClassLookupTable: [:],
      moduleJavaPackages: [:]
    )
    try generator.writeSwiftThunkSources(&printer)
    let output = printer.finalize()
    let gotLines = output.components(separatedBy: .whitespacesAndNewlines)

    #expect(
      gotLines.count(where: { line in
        line == #"@_cdecl("Java_com_example_swift_DeliveryStage__00024getRawValue__J")"#
      }) == 1,
      "Invalid redeclaration detected."
    )
  }
}
