//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2025 Apple Inc. and the Swift.org project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of Swift.org project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import JExtractSwiftLib
import Testing

@Suite
struct JNIModuleTests {
  let globalMethodWithPrimitives = """
    public func helloWorld()
    public func takeIntegers(i1: Int8, i2: Int16, i3: Int32, i4: Int) -> UInt16
    public func otherPrimitives(b: Bool, f: Float, d: Double)
  """

  @Test
  func generatesModuleJavaClass() throws {
    let input = "public func helloWorld()"

    try assertOutput(input: input, .jni, .java, expectedChunks: [
      """
      // Generated by jextract-swift
      // Swift module: SwiftModule

      package com.example.swift;

      public final class SwiftModule {
      """
    ])
  }

  @Test
  func globalMethodWithPrimitives_javaBindings() throws {
    try assertOutput(
      input: globalMethodWithPrimitives,
      .jni,
      .java,
      expectedChunks: [
        """
        /**
          * Downcall to Swift:
          * {@snippet lang=swift :
          * public func helloWorld()
          * }
          */
        public static native void helloWorld();
        """,
        """
        /**
          * Downcall to Swift:
          * {@snippet lang=swift :
          * public func takeIntegers(i1: Int8, i2: Int16, i3: Int32, i4: Int) -> UInt16
          * }
          */
        public static native char takeIntegers(byte i1, short i2, int i3, long i4);
        """,
        """
        /**
          * Downcall to Swift:
          * {@snippet lang=swift :
          * public func otherPrimitives(b: Bool, f: Float, d: Double)
          * }
          */
        public static native void otherPrimitives(boolean b, float f, double d);
        """
      ]
    )
  }

  @Test
  func globalMethodWithPrimitives_swiftThunks() throws {
    try assertOutput(
      input: globalMethodWithPrimitives,
      .jni,
      .swift,
      detectChunkByInitialLines: 1,
      expectedChunks: [
        """
        @_cdecl("Java_com_example_swift_SwiftModule_helloWorld")
        func swiftjava_SwiftModule_helloWorld(environment: UnsafeMutablePointer<JNIEnv?>!, thisClass: jclass) {
          SwiftModule.helloWorld()
        }
        """,
        """
        @_cdecl("Java_com_example_swift_SwiftModule_takeIntegers")
        func swiftjava_SwiftModule_takeIntegers_i1_i2_i3_i4(environment: UnsafeMutablePointer<JNIEnv?>!, thisClass: jclass, i1: jbyte, i2: jshort, i3: jint, i4: jlong) -> jchar {
          let result = SwiftModule.takeIntegers(i1: Int8(fromJNI: i1, in: environment!), i2: Int16(fromJNI: i2, in: environment!), i3: Int32(fromJNI: i3, in: environment!), i4: Int(fromJNI: i4, in: environment!))
          return result.getJNIValue(in: environment)")
        }
        """,
        """
        @_cdecl("Java_com_example_swift_SwiftModule_otherPrimitives")
        func swiftjava_SwiftModule_otherPrimitives_b_f_d(environment: UnsafeMutablePointer<JNIEnv?>!, thisClass: jclass, b: jboolean, f: jfloat, d: jdouble) {
          SwiftModule.otherPrimitives(b: Bool(fromJNI: b, in: environment!), f: Float(fromJNI: f, in: environment!), d: Double(fromJNI: d, in: environment!))
        }
        """
      ]
    )
  }
}
