//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2025 Apple Inc. and the Swift.org project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of Swift.org project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import JExtractSwiftLib
import Testing

@Suite
struct JNIStructTests {
  let source = """
      public struct MyStruct {
        let x: Int64
        let y: Int64

        public init(x: Int64, y: Int64) {
          self.x = y
          self.y = y
        }

        public func doSomething(x: Int64) {}
      }
    """

  @Test
  func generatesJavaClass() throws {
    try assertOutput(
      input: source, .jni, .java,
      expectedChunks: [
        """
        // Generated by jextract-swift
        // Swift module: SwiftModule

        package com.example.swift;

        import org.swift.swiftkit.core.*;
        import org.swift.swiftkit.core.util.*;
        """,])
      try assertOutput(input: source, .jni, .java, expectedChunks: [
        """
        public final class MyStruct implements JNISwiftInstance {
          static final String LIB_NAME = "SwiftModule";

          @SuppressWarnings("unused")
          private static final boolean INITIALIZED_LIBS = initializeLibs();
          static boolean initializeLibs() {
            System.loadLibrary(LIB_NAME);
            return true;
          }
        """,
        """
        private MyStruct(long selfPointer, SwiftArena swiftArena) {
          SwiftObjects.requireNonZero(selfPointer, "selfPointer");
          this.selfPointer = selfPointer;
        
          // Only register once we have fully initialized the object since this will need the object pointer.
          swiftArena.register(this);
        }
        """,
        """
        public static MyStruct wrapMemoryAddressUnsafe(long selfPointer, SwiftArena swiftArena) {
          return new MyStruct(selfPointer, swiftArena);
        }
        """
      ])
    try assertOutput(
      input: source, .jni, .java,
      expectedChunks: [
        """
        private static native void $destroy(long selfPointer);
        """
      ])
    try assertOutput(
      input: source, .jni, .java,
      expectedChunks: [
        """
        @Override
        public Runnable $createDestroyFunction() {
          long self$ = this.$memoryAddress();
          if (CallTraces.TRACE_DOWNCALLS) {
            CallTraces.traceDowncall("MyStruct.$createDestroyFunction",
                "this", this,
                "self", self$);
          }
          return new Runnable() {
            @Override
            public void run() {
              if (CallTraces.TRACE_DOWNCALLS) {
                CallTraces.traceDowncall("MyStruct.$destroy", "self", self$);
              }
              MyStruct.$destroy(self$);
            }
          };
        }
        """
      ])
  }

  @Test
  func initializer_javaBindings() throws {
    try assertOutput(
      input: source,
      .jni,
      .java,
      expectedChunks: [
        """
        /**
         * Downcall to Swift:
         * {@snippet lang=swift :
         * public init(x: Int64, y: Int64)
         * }
         */
        public static MyStruct init(long x, long y, SwiftArena swiftArena$) {
          return MyStruct.wrapMemoryAddressUnsafe(MyStruct.$init(x, y), swiftArena$);
        }
        """,
        """
        private static native long $init(long x, long y);
        """,
      ]
    )
  }

  @Test
  func initializer_swiftThunks() throws {
    try assertOutput(
      input: source,
      .jni,
      .swift,
      detectChunkByInitialLines: 1,
      expectedChunks: [
        """
        @_cdecl("Java_com_example_swift_MyStruct__00024init__JJ")
        func Java_com_example_swift_MyStruct__00024init__JJ(environment: UnsafeMutablePointer<JNIEnv?>!, thisClass: jclass, x: jlong, y: jlong) -> jlong {
          let result$ = UnsafeMutablePointer<MyStruct>.allocate(capacity: 1)
          result$.initialize(to: MyStruct.init(x: Int64(fromJNI: x, in: environment!), y: Int64(fromJNI: y, in: environment!)))
          let resultBits$ = Int64(Int(bitPattern: result$))
          return resultBits$.getJNIValue(in: environment!)
        }
        """
      ]
    )
  }

  @Test
  func destroyFunction_swiftThunks() throws {
    try assertOutput(
      input: source,
      .jni,
      .swift,
      expectedChunks: [
        """
        @_cdecl("Java_com_example_swift_MyStruct__00024destroy__J")
        func Java_com_example_swift_MyStruct__00024destroy__J(environment: UnsafeMutablePointer<JNIEnv?>!, thisClass: jclass, selfPointer: jlong) {
          guard let env$ = environment else {
            fatalError("Missing JNIEnv in downcall to \\(#function)")
          }
          assert(selfPointer != 0, "selfPointer memory address was null")
          let selfBits$ = Int(Int64(fromJNI: selfPointer, in: env$))
          guard let self$ = UnsafeMutablePointer<MyStruct>(bitPattern: selfBits$) else {
            fatalError("self memory address was null in call to \\(#function)!")
          }
          self$.deinitialize(count: 1)
          self$.deallocate()
        }
        """
      ]
    )
  }

  @Test
  func memberMethod_javaBindings() throws {
    try assertOutput(
      input: source,
      .jni,
      .java,
      expectedChunks: [
        """
        /**
         * Downcall to Swift:
         * {@snippet lang=swift :
         * public func doSomething(x: Int64)
         * }
         */
        public void doSomething(long x) {
          MyStruct.$doSomething(x, this.$memoryAddress());
        }
        """,
        """
        private static native void $doSomething(long x, long self);
        """,
      ]
    )
  }

  @Test
  func memberMethod_swiftThunks() throws {
    try assertOutput(
      input: source,
      .jni,
      .swift,
      detectChunkByInitialLines: 1,
      expectedChunks: [
        """
        @_cdecl("Java_com_example_swift_MyStruct__00024doSomething__JJ")
        func Java_com_example_swift_MyStruct__00024doSomething__JJ(environment: UnsafeMutablePointer<JNIEnv?>!, thisClass: jclass, x: jlong, self: jlong) {
          assert(self != 0, "self memory address was null")
          let selfBits$ = Int(Int64(fromJNI: self, in: environment!))
          let self$ = UnsafeMutablePointer<MyStruct>(bitPattern: selfBits$)
          guard let self$ else {
            fatalError("self memory address was null in call to \\(#function)!")
          }
          self$.pointee.doSomething(x: Int64(fromJNI: x, in: environment!))
        }
        """
      ]
    )
  }
}
