//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2024 Apple Inc. and the Swift.org project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of Swift.org project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import SwiftJavaJNICore

extension JavaType {

  /// The maximum supported tuple arity.
  static let maxTupleArity = 24

  /// The description of the type org.swift.swiftkit.core.tuple.TupleN<T0, T1, ...>
  static func tuple(elementTypes: [JavaType]) -> JavaType {
    let arity = elementTypes.count
    guard arity <= maxTupleArity else {
      fatalError("Tuple arity \(arity) exceeds maximum supported arity of \(maxTupleArity)")
    }
    return .class(
      package: "org.swift.swiftkit.core.tuple",
      name: "Tuple\(arity)",
      typeParameters: elementTypes.map(\.boxedType)
    )
  }

  /// The description of a labeled tuple type: LabeledTuple_someName_a_b_c<T0, T1, ...>
  static func labeledTuple(_ baseName: String, names: [String], elementTypes: [JavaType]) -> JavaType {
    assert(names.count == elementTypes.count, "Names count (\(names.count)) must be equal types count (\(elementTypes.count))")

    let arity = elementTypes.count
    guard arity <= maxTupleArity else {
      fatalError("Tuple arity \(arity) exceeds maximum supported arity of \(maxTupleArity)")
    }
    let joinedNames = names.joined(separator: "_")
    return .class(
      package: nil,
      name: "LabeledTuple_\(baseName)_\(joinedNames)",
      typeParameters: elementTypes.map(\.boxedType)
    )
  }

  /// Whether this type is a labeled tuple type generated by swift-java
  var isSwiftJavaLabeledTuple: Bool {
    if case .class(_, let name, _) = self {
      return name.hasPrefix("LabeledTuple_")
    }
    return false
  }
}
